export const CardBackgroundImages = [
  require("../assets/images/card-images/1.jpeg"),
  require("../assets/images/card-images/2.jpeg"),
  require("../assets/images/card-images/3.jpeg"),
  require("../assets/images/card-images/4.jpeg"),
  require("../assets/images/card-images/5.jpeg"),
  require("../assets/images/card-images/6.jpeg"),
  require("../assets/images/card-images/7.jpeg"),
  require("../assets/images/card-images/8.jpeg"),
  require("../assets/images/card-images/9.jpeg"),
  require("../assets/images/card-images/10.jpeg"),
  require("../assets/images/card-images/11.jpeg"),
  require("../assets/images/card-images/12.jpeg"),
  require("../assets/images/card-images/13.jpeg"),
  require("../assets/images/card-images/14.jpeg"),
  require("../assets/images/card-images/15.jpeg"),
  require("../assets/images/card-images/16.jpeg"),
  require("../assets/images/card-images/17.jpeg"),
  require("../assets/images/card-images/18.jpeg"),
  require("../assets/images/card-images/19.jpeg"),
  require("../assets/images/card-images/20.jpeg"),
  require("../assets/images/card-images/21.jpeg"),
  require("../assets/images/card-images/22.jpeg"),
  require("../assets/images/card-images/23.jpeg"),
  require("../assets/images/card-images/24.jpeg"),
  require("../assets/images/card-images/25.jpeg"),
];

export const CardManufacturer = {
  amex: require("../assets/images/card-images/amex.png"),
  dinersclub: require("../assets/images/card-images/dinersclub.png"),
  discover: require("../assets/images/card-images/discover.png"),
  jcb: require("../assets/images/card-images/jcb.png"),
  mastercard: require("../assets/images/card-images/mastercard.png"),
  troy: require("../assets/images/card-images/troy.png"),
  unionpay: require("../assets/images/card-images/unionpay.png"),
  visa: require("../assets/images/card-images/visa.png"),
};
