export const CardBackgroundImages = [
  require("../assets/images/card-images/1.jpeg"),
  require("../assets/images/card-images/2.jpeg"),
  require("../assets/images/card-images/3.jpeg"),
  require("../assets/images/card-images/4.jpeg"),
  require("../assets/images/card-images/5.jpeg"),
  require("../assets/images/card-images/6.jpeg"),
  require("../assets/images/card-images/7.jpeg"),
  require("../assets/images/card-images/8.jpeg"),
  require("../assets/images/card-images/9.jpeg"),
  require("../assets/images/card-images/10.jpeg"),
  require("../assets/images/card-images/11.jpeg"),
  require("../assets/images/card-images/12.jpeg"),
  require("../assets/images/card-images/13.jpeg"),
  require("../assets/images/card-images/14.jpeg"),
  require("../assets/images/card-images/15.jpeg"),
  require("../assets/images/card-images/16.jpeg"),
  require("../assets/images/card-images/17.jpeg"),
  require("../assets/images/card-images/18.jpeg"),
  require("../assets/images/card-images/19.jpeg"),
  require("../assets/images/card-images/20.jpeg"),
  require("../assets/images/card-images/21.jpeg"),
  require("../assets/images/card-images/22.jpeg"),
  require("../assets/images/card-images/23.jpeg"),
  require("../assets/images/card-images/24.jpeg"),
  require("../assets/images/card-images/25.jpeg"),
];

export const CardManufacturer = {
  "1": require("../assets/images/card-images/amex.png"),
  "2": require("../assets/images/card-images/dinersclub.png"),
  "3": require("../assets/images/card-images/discover.png"),
  "4": require("../assets/images/card-images/jcb.png"),
  "5": require("../assets/images/card-images/mastercard.png"),
  "6": require("../assets/images/card-images/troy.png"),
  "7": require("../assets/images/card-images/unionpay.png"),
  "8": require("../assets/images/card-images/visa.png"),
};
